apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: smart-home-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/rupal-draft/Smart-Home-Automation-Backend.git"
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
